spin_manifest_version = 2

[application]
authors = ["Yordan Madzhunkov"]
name = "Etherium RPC"
version = "0.1.0"

[application.trigger.settings]
interval_time_in_seconds = 90
reporter_id = 0
sequencer = "http://127.0.0.1:8877/post_reports_batch"
secret_key = "536d1f9d97166eba5ff0efb8cc8dbeb856fb13d2d126ed1efc761e9955014003"
second_consensus_secret_key = "ac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
kafka_endpoint = "http://127.0.0.1:9092"

[[trigger.oracle]]
component = "eth-rpc"

[[trigger.oracle.data_feeds]]
id = "100001"
stride = 0
decimals = 0
data = '{"pair":{"base":"","quote":""},"decimals":0,"category":"","market_hours":"Crypto","arguments":[]}'

[component.eth-rpc]
source = "../../../target/wasm32-wasip1/release/eth_rpc.wasm"
allowed_outbound_hosts = [
  "https://eth.llamarpc.com",
  "https://rpc.eth.gateway.fm",
]

[component.eth-rpc.build]
command = "cargo build --target wasm32-wasip1 --release"
